version : '3'
services :
  server1 :
    build: .
    ports :
      - "5001:5000"

  server2 :
    build: .
    ports :
      - "5002:5000"
  
  server3 :
    build: .
    ports :
      - "5003:5000"


  client :
    build: Dockerfile2
    ports :
      - "5000:5000"
  
  web:
  image: nginx
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  command: [nginx-debug, '-g', 'daemon off;']

